services:
  webradio:
    image: teleram/webradio:latest
    container_name: webradio
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./data/recordings:/app/recordings
      - ./data/images:/app/static/images
      - ./data/webradio.db:/data/webradio.db
      - /etc/localtime:/etc/localtime:ro  # Mount host timezone (read-only)
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:////data/webradio.db
      - RECORDINGS_DIR=/app/recordings
      - UPLOAD_FOLDER=/app/static/images
      - TZ=Europe/London  # Set your timezone here (change as needed)
    networks:
      - webradio-network

networks:
  webradio-network:
    driver: bridge
