services:
  webradio2:
    image: teleram/webradio:latest
    container_name: webradio2
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./recordings:/app/recordings
      - ./images:/app/static/images
      - ./data:/data
      - ./local:/localrec
#      - /etc/localtime:/etc/localtime:ro  # Mount host timezone (read-only)
#      - /etc/timezone:/etc/timezone:ro

    environment:
      - DATABASE_URL=sqlite:////data/webradio.db
      - DATABASE_PATH=/data/webradio.db
      - RECORDINGS_DIR=/app/recordings
      - UPLOAD_FOLDER=/app/static/images
      - TZ=Europe/Athens 
      - SECRET_KEY=KarapiperimPiperimPiperim
      - LOG_LEVEL=WARNING
    networks:
      - dockernet


networks:
  dockernet:
    name: dockernet
    external: true
